DEFAULT = 'default'
REQUIRED = 'required'
UNIQUE = 'unique'
READ_ONLY = 'read_only'
WRITE_ONLY = 'write_only'
ALLOW_NULL = 'allow_null'
ALLOW_BLANK = 'allow_blank'
VALIDATOR = 'validator'

TYPE = 'type'

BASE = 'base'
MAX_VALUE = 'max_value'
MIN_VALUE = 'min_value'
NUMERIC = 'numeric'
INTEGER = 'integer'
POSITIVE_INTEGER = 'positive_integer'
NEGATIVE_INTEGER = 'negative_integer'
FLOAT = 'float'
POSITIVE_FLOAT = 'positive_float'
NEGATIVE_FLOAT = 'negative_float'

MAX_LENGTH = 'max_length'
MIN_LENGTH = 'min_length'
STRING = 'string'
EMAIL = 'email'
PASSWORD = 'password'
GENDER = 'gender'
URL = 'url'
LIST = 'list'
DICTIONARY = 'dictionary'
TUPLE = 'tuple'
SET = 'set'
BOOLEAN = 'boolean'
USERNAME = 'username'
ALL = '__all__'
